#! /bin/bash

echo "$BASHPID" > /run/cgid.pid

if [[ ! -d '/tmp/librerouter/sess/list/' ]]
then
	mkdir -p /tmp/librerouter/sess/list/
fi
while true
do
	for i in `ls /tmp/librerouter/sess/list/`
	do
		ip=`cat /tmp/librerouter/sess/list/"${i}"`
#		[[ ! -f "/tmp/librerouter/sess/${ip}/${i}/cgi.in" ]] && continue
		outpipe=/tmp/librerouter/sess/"${ip}"/"${i}"/cgi.out
		inpipe=/tmp/librerouter/sess/"${ip}"/"${i}"/cgi.in
		export UIPATH="/opt/librerouter/webui"
		trap "rm -f $outpipe;rm -f /run/cgid.pid" EXIT
		[[ ! -p "$outpipe" ]] && mkfifo "$outpipe"
#		if [[ ! -p "$inpipe" ]]
#		then
#			echo "Error: Failed to find input pipe, Exiting."
#			exit
#		fi
		if read line <"$inpipe"
		then
			input=`echo "${line}" | tr -d '$,(,),{,},\`,|,/,<,>,%,#,@,!'`
			module=`echo "${input}" | awk -F '::' '{print $1}' | tr -d ' '`
			parms=`echo "${input}" | awk -F '::' '{print $2}'`
			cd "$UIPATH"/sh/"${module}"/
			if [[ ! -e "./main.exec" ]]
			then
				echo "1 :: Error: Module main execution failed - missing main script." > "${outpipe}"
			else
				echo executing
				./main.exec "${parms}" > "${outpipe}"
			fi
		fi
		rm -f "${inpipe}"
		rm -f /tmp/librerouter/sess/list/"${i}"
	done
done
