#!/bin/bash

ROOTMOUNT="$1"
if [ "$ROOTMOUNT" = "" ]
then
	ROOTMOUNT="/"
fi

ROOTPART=`mount | grep " $ROOTMOUNT " | awk '{print $1}'`
ROOTMBR=`echo $ROOTPART | sed -e 's/[0-9]*//g'`
GRUBLOCTEST="$2"
if [ "$GRUBLOCTEST" = "root" ]
then
	GRUBLOC="$ROOTPART"
elif [ "$GRUBLOCTEST" = "rootmbr" ]
then
	GRUBLOC="$ROOTMBR"
else
	GRUBLOC=`echo "$1" | sed -e 's/[0-9]*//g' | sed -e 's/\/mnt//g'`
	GRUBLOC=`echo "/dev$GRUBLOC"`
fi



if [ "$ROOTMOUNT" != "/" ]; then

	if [ ! -e $ROOTMOUNT/proc/cpuinfo ]
	then
		STANDALONE="yes"
		mount -o bind /proc $ROOTMOUNT/proc
		mount -o bind /dev $ROOTMOUNT/dev
		mount -o bind /sys $ROOTMOUNT/sys
	fi
	chroot $ROOTMOUNT grub-install --no-floppy $GRUBLOC
	chroot $ROOTMOUNT update-grub
	sync
	if [ "$STANDALONE" = "yes" ]
	then
		sleep 1
		umount $ROOTMOUNT/proc
		sleep 1
		umount $ROOTMOUNT/dev
		sleep 1
		umount $ROOTMOUNT/sys
		sleep 1
	fi
else
	grub-install --no-floppy $GRUBLOC
	update-grub
	sync
fi