.TH man 8 "1 Mar 2014" "1.01" "utsc man page"
.SH NAME
UTSC \- Unix Time Support Compatibility initializer for SphinUX OS.
.SH VERSION
1.01
.SH SYNOPSIS
utsc OPTION ...
.SH DESCRIPTION
This will automate the process of writing the configuration to the utsc watch daemon.

The UTSC watch deamon provides a secure interface to change the uts_namespace() values.
init would run it at runlevel 3, and it would be respawned so that modifications to the values are done only through the daemon.
.SH OPTIONS
on				Enable utsc for Linux uts_namespace 'set the uts_sysname to Linux'.

off				Disable utsc support for Linux uts_namespace 'revert the uts_sysname value to Sphinux'.

-s SYSNAME		Set uts_sysname value to SYSNAME.

-r RELEASE		Set uts_release value to RELEASE.

-v VERSION		Set uts_version value to VERSION.

-h,--help			Print usage information.

.SH BUGS
No known bugs.

Report bugs to <bugs@sphinux.org>.
.SH AUTHOR
Ahmed G. Elneel [SibirskiyVolk] .

.SH COPYRIGHT
Copyright \(co 2014 SphinUX Community, Alexandria, Egypt.

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.