#!/bin/sh
### BEGIN INIT INFO
# Provides:          cgid
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# X-Start-Before:    lighttpd
# X-Stop-After:      lighttpd
# Default-Start:     2 3 4 5
# Default-Stop:	   
# Short-Description: Start the cgi FIFO buffer daemon
# Description:       Executes WEBUI shell modlues
#                    as root from the FIFO buffer
### END INIT INFO

set -e

CGID="/usr/sbin/cgid"

# Check for daemon presence
[ -x "$CGID" ] || exit 0

OPTIONS=""

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    $0 stop
    log_begin_msg "Starting CGI Daemon ..."
    start-stop-daemon --start --quiet -b --oknodo --exec "$CGID"
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping CGI Daemon ..."
    start-stop-daemon --stop --quiet --oknodo --retry 2 --pidfile /run/cgid.pid
    log_end_msg $?
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  reload|force-reload)
    log_begin_msg "Reloading CGI Daemon ..."
    $0 stop
    $0 start
    log_end_msg $?
    ;;
  status)
    status_of_proc "$CGID" cgid
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/cgid {start|stop|restart|reload|force-reload|status}"
    exit 1
esac
